image: r-base

before_script:
  - apt-get update
  - apt-get -y install libcurl4-openssl-dev libssl-dev libxml2-dev libglu1-mesa-dev libssh2-1-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev libgit2-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev pandoc r-cran-rcpp r-cran-devtools r-cran-testthat r-cran-curl r-cran-seqinr r-cran-ape r-bioc-biostrings r-cran-uuid r-cran-callr
  - R -e "dir(); getwd(); sessionInfo(); install.packages('pkgdown', repos='http://cran.rstudio.com'); devtools::install_github('tnagler/RcppThread'); Rcpp::compileAttributes(); devtools::install()"

pages:
  stage: deploy
  script:
    - R -e "dir(); getwd(); Rcpp::compileAttributes(); devtools::install(); sessionInfo(); pkgdown::build_site()"
  artifacts:
    paths:
      - public
  only:
    - master
