# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib distSTRING, .registration = TRUE
#' @import Rcpp
#' @import RcppThread
#' @export rcpp_distSTRING
#' @author Kristian K Ullrich
rcpp_distSTRING <- function(dnavector, scoreMatrix, ncores = 1L) {
    .Call(`_distSTRING_rcpp_distSTRING`, dnavector, scoreMatrix, ncores)
}

#' @useDynLib distSTRING, .registration = TRUE
#' @import Rcpp
#' @import RcppThread
#' @export rcpp_pairwiseDeletionAA
#' @author Kristian K Ullrich
rcpp_pairwiseDeletionAA <- function(aavector, ncores = 1L) {
    .Call(`_distSTRING_rcpp_pairwiseDeletionAA`, aavector, ncores)
}

#' @useDynLib distSTRING, .registration = TRUE
#' @import Rcpp
#' @import RcppThread
#' @export rcpp_pairwiseDeletionDNA
#' @author Kristian K Ullrich
rcpp_pairwiseDeletionDNA <- function(dnavector, ncores = 1L) {
    .Call(`_distSTRING_rcpp_pairwiseDeletionDNA`, dnavector, ncores)
}

#' @useDynLib distSTRING, .registration = TRUE
#' @import Rcpp
#' @import RcppThread
#' @export rcpp_vol
#' @author Kristian K Ullrich
rcpp_vol <- function(inputMatrix, ncores = 1L) {
    .Call(`_distSTRING_rcpp_vol`, inputMatrix, ncores)
}

